
package com.itheima.crm.service.impl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomerServiceImpl", targetNamespace = "http://impl.service.crm.itheima.com/")
public interface CustomerServiceImpl {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "activeMail", targetNamespace = "http://impl.service.crm.itheima.com/", className = "com.itheima.crm.service.impl.ActiveMail")
    @ResponseWrapper(localName = "activeMailResponse", targetNamespace = "http://impl.service.crm.itheima.com/", className = "com.itheima.crm.service.impl.ActiveMailResponse")
    public void activeMail(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.itheima.crm.service.impl.Customer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByTelephone", targetNamespace = "http://impl.service.crm.itheima.com/", className = "com.itheima.crm.service.impl.FindByTelephone")
    @ResponseWrapper(localName = "findByTelephoneResponse", targetNamespace = "http://impl.service.crm.itheima.com/", className = "com.itheima.crm.service.impl.FindByTelephoneResponse")
    public Customer findByTelephone(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.itheima.crm.service.impl.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByFixedAreaId", targetNamespace = "http://impl.service.crm.itheima.com/", className = "com.itheima.crm.service.impl.FindByFixedAreaId")
    @ResponseWrapper(localName = "findByFixedAreaIdResponse", targetNamespace = "http://impl.service.crm.itheima.com/", className = "com.itheima.crm.service.impl.FindByFixedAreaIdResponse")
    public List<Customer> findByFixedAreaId(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "assignCustomers2FixedArea", targetNamespace = "http://impl.service.crm.itheima.com/", className = "com.itheima.crm.service.impl.AssignCustomers2FixedArea")
    @ResponseWrapper(localName = "assignCustomers2FixedAreaResponse", targetNamespace = "http://impl.service.crm.itheima.com/", className = "com.itheima.crm.service.impl.AssignCustomers2FixedAreaResponse")
    public void assignCustomers2FixedArea(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<Integer> arg1);

    /**
     * 
     * @return
     *     returns java.util.List<com.itheima.crm.service.impl.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://impl.service.crm.itheima.com/", className = "com.itheima.crm.service.impl.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://impl.service.crm.itheima.com/", className = "com.itheima.crm.service.impl.FindAllResponse")
    public List<Customer> findAll();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findFixedAreaIdByAddress", targetNamespace = "http://impl.service.crm.itheima.com/", className = "com.itheima.crm.service.impl.FindFixedAreaIdByAddress")
    @ResponseWrapper(localName = "findFixedAreaIdByAddressResponse", targetNamespace = "http://impl.service.crm.itheima.com/", className = "com.itheima.crm.service.impl.FindFixedAreaIdByAddressResponse")
    public String findFixedAreaIdByAddress(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.itheima.crm.service.impl.Customer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://impl.service.crm.itheima.com/", className = "com.itheima.crm.service.impl.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://impl.service.crm.itheima.com/", className = "com.itheima.crm.service.impl.LoginResponse")
    public Customer login(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "regist", targetNamespace = "http://impl.service.crm.itheima.com/", className = "com.itheima.crm.service.impl.Regist")
    @ResponseWrapper(localName = "registResponse", targetNamespace = "http://impl.service.crm.itheima.com/", className = "com.itheima.crm.service.impl.RegistResponse")
    public void regist(
        @WebParam(name = "arg0", targetNamespace = "")
        Customer arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.itheima.crm.service.impl.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByFixedAreaIdIsNull", targetNamespace = "http://impl.service.crm.itheima.com/", className = "com.itheima.crm.service.impl.FindByFixedAreaIdIsNull")
    @ResponseWrapper(localName = "findByFixedAreaIdIsNullResponse", targetNamespace = "http://impl.service.crm.itheima.com/", className = "com.itheima.crm.service.impl.FindByFixedAreaIdIsNullResponse")
    public List<Customer> findByFixedAreaIdIsNull();

}
